sh: 1: Syntax error: Bad fd number
results_run0000/
folder=  results_run0000/
Traceback (most recent call last):
  File "run_multi_leon_sims_1.py", line 158, in run_simulation
    storeFiles(global_dict)
  File "run_multi_leon_sims_1.py", line 69, in storeFiles
    shutil.copy(gd["base_dest_folder"]+"/data_baseline_p0.txt", dfolder)
  File "/home/five_crows/anaconda3/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/five_crows/anaconda3/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'data_ge//results//data_baseline_p0.txt'
-----------------------------------------------
repeat_run=  0
nb_repeat_runs=  1
top_level_run=  0
run=  0
dct=  {'vacc1_rate': 0, 'max_nb_avail_doses': 50000, 'epsilonSinv': 2.0, 'muinv': 3.0, 'R0': 2.0, 'beta_shape': 2.0, 'beta_scale': 3.0}
global_dict:  {'base_dest_folder': 'data_ge//results/', 'dest_folder': 'data_ge//project00001/', 'output_file': 'output.txt', 'source_folder': 'data_ge/', 'script_file': 'run_leon_simulations.py', 'timestamp': '02_01_18_40_24', 'param_file': 'data_ge/parameters_0.txt', 'state_transition_file': 'transition_stats.csv', 'counts_file': 'counts.csv', 'nb_repeat_runs': 1, 'project_nb': 1, 'search_params': {'vacc1_rate': [0], 'max_nb_avail_doses': [50000], 'epsilonSinv': [2.0], 'muinv': [3.0], 'R0': [2.0], 'beta_shape': [2.0], 'beta_scale': [3.0]}, 'run_description': 'Project1: No vaccinations. Test the shape of the infectivity profile as a function of the Weibull shape and scale parameter values. Test three values of R0.', 'N': 260542.0, 'r': 0.0, 'epsilonA-1': 0.0, 'epsilonS-1': 2.0, 'p': 0.0, 'gamma-1': 20.0, 'mu-1': 5.0, 'alpha0': 0.0, 'alpha1': 0.0, 'alpha2': 0.0, 'alpha3': 0.0, 'alpha4': 0.0, 'xi0': 0.0, 'xi1': 0.0, 'xi2': 0.0, 'xi3': 0.0, 'xi4': 0.0, 'delta': 2.0, 'muH-1': 8.0, 'muICU-1': 13.0, 'k': 0.15, 'beta': 0.2, 'dt': 0.1, 'vac1_rate': 10000.0, 'vac2_rate': 0.0, 'vac1_effectiveness': 0.6, 'vac2_effectiveness': 0.95, 'dt_btw_vacc': 28.0, 'top_level_run': 0, 'run': 0, 'leaf_folder': 'results_run0000/', 'repeat_run': 0, 'vacc1_rate': 0, 'max_nb_avail_doses': 50000, 'epsilonSinv': 2.0, 'muinv': 3.0, 'R0': 2.0, 'beta_shape': 2.0, 'beta_scale': 3.0, 'cmd': '/bin/bash  ./seir --vacc1_rate 0 --max_nb_avail_doses 50000 --epsilonSinv 2.0 --muinv 3.0 --R0 2.0 --beta_shape 2.0 --beta_scale 3.0 >& data_ge//project00001/results_run0000/output.txt'}
command:  /bin/bash  ./seir --vacc1_rate 0 --max_nb_avail_doses 50000 --epsilonSinv 2.0 --muinv 3.0 --R0 2.0 --beta_shape 2.0 --beta_scale 3.0 >& data_ge//project00001/results_run0000/output.txt 
sfolder=  data_ge/
dfolder=  data_ge//project00001/results_run0000/
state_tran=  transition_stats.csv
base_dst_folder=  data_ge//results//data_baseline_p0.txt
An error occurred during execution
cmd=  cd data_ge//project00001/; python breakup_transition.py;
